# Site Settings
title: "Game Boy Essentials"
domain: "gameboyessentials.com"
url: "https://gameboyessentials.com"
baseurl: ""
email: "pl@gameboyessentials.com"
twitter: "@supergbe"
icon-512: "/apple-touch-icon.png"
description: "A project to review and talk about the essential games you should play on Game Boy to understand its appeal and its success."
exclude: [/drafts, /_tags, /_site-local, /_folio/test-suite.md, /assets/0test, /projects]
incremental: false

## Use of Collections for my articles
collections:
  articles:
    output: true
    permalink: /articles/:title/
  folio:
    output: true
    permalink: /:slug/
  tags:
    output: true
    permalink: tag/:title/
defaults:
  -
    scope:
      path: ""
      type: articles
    values:
      layout: article
      article: true
  -
    scope:
      path: "drafts"
    values:
      layout: article
      article: true
  -
    scope:
      path: ""
      type: tags
    values:
      layout: tags

## Markdown
markdown: kramdown
kramdown:
  entity_output: as_input

## SASS
sass:
  sourcemap: never

## Plugins
plugins:
  - jekyll-redirect-from
  - jekyll-image-size
  
## Redirect-From
redirect_from:
  json: false