# Site Settings
title: "Game Boy Essentials"
url: "https://gameboyessentials.com"
baseurl: ""
email: "pl@gameboyessentials.com"
twitter: "@supergbe"
icon-512: "/apple-touch-icon.png"
description: "A project to review and talk about the essential games you must play on Game Boy to understand its appeal and its success. Not only the best games for the system, but also the bad games that enlighten the legacy of the most popular video game console of the 1990s."
source: "/Users/plgagne/Documents/Game Boy Essentials"
destination: "/Users/plgagne/Documents/Game Boy Essentials/website"
exclude: [/website, /website-serve]
incremental: true

## Use of Collections for my articles
collections:
  articles:
    output: true
    permalink: /articles/:title/
  folio:
    output: true
    permalink: /:title/
defaults:
  -
    scope:
      path: ""
      type: articles
    values:
      layout: article
      article: true
  -
    scope:
      path: "drafts"
    values:
      layout: article
      article: true

## Markdown
markdown: kramdown
kramdown:
  entity_output: as_input

## SASS
sass:
  sourcemap: never

## Plugins
plugins:
  - jekyll-redirect-from
  - jekyll-image-size