# frozen_string_literal: true
source "https://rubygems.org"

# gem "jekyll"
gem "github-pages", "~> 227", group: :jekyll_plugins

group :jekyll_plugins do
  gem 'jekyll-redirect-from'
  gem 'jekyll-image-size'
end