# frozen_string_literal: true
source "https://rubygems.org"

gem "jekyll"

# The gems removed from standard lib of Ruby that Jekyll can't fucking seem to bother to fix
gem "logger"

group :jekyll_plugins do
  gem 'jekyll-image-size'
  gem 'jekyll-last-modified-at'
end